[package]
name = "select_playground"
version = "0.0.0"
edition = "2024"

[dependencies]
futures = "0.3.31"
rand = "0.9.2"
tokio = { version = "1.48.0", features = ["full"] }

[[bin]]
name = "select"
path = "select.rs"
