[package]
name = "render_posts"
version = "0.0.0"
edition = "2024"

[profile.release]
debug = true

[dependencies]
anyhow = "1.0.69"
html-escape = "0.2.13"
pulldown-cmark = "0.13.0"
serde = { version = "1.0.208", features = ["derive"] }
syntect = "5.0.0"
toml = "1.0.1"
url = "2.5.2"
